# Generated by Django 4.0.6 on 2022-07-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('password', models.EmailField(max_length=1000)),
                ('slug', models.SlugField(max_length=1000)),
            ],
        ),
    ]
